---

# Bitbucket base URL to check
bitbucket_base_url: ""

# ADO base URL, with ORG
ado_base_url: ""

# ADO REST API Version
ado_api_version: ""

# ADO project
ado_project: ""

# Bitbucket CSV file path
bb_repo_csv: ""
